// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EcdictIsAvailable checks if the ECDICT database is ready
 */
export function EcdictIsAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(1239624116);
}

/**
 * ImportEcdict imports ECDICT CSV into SQLite database.
 * Supports both .csv and .csv.gz formats. csvPath can be empty for auto-search.
 * Uses batch multi-row INSERT for maximum throughput (~100K rows/sec).
 */
export function ImportEcdict(csvPath: string): $CancellablePromise<void> {
    return $Call.ByID(741374516, csvPath);
}

/**
 * LookupEcdict looks up a word in ECDICT. Returns nil if not found or DB unavailable.
 * Uses case-insensitive matching by trying the lowercase form first (index-friendly),
 * then falls back to COLLATE NOCASE only if needed.
 */
export function LookupEcdict(word: string): $CancellablePromise<$models.EcdictEntry | null> {
    return $Call.ByID(1915349047, word);
}
