// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService manages the local word book using SQLite.
 * It replaces the old JSON-file-based history with proper database storage,
 * enabling reliable persistence and sync support.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../database/sql/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddHistory adds a new entry or updates an existing one (same word).
 * If skipSync is true, the sync callback is NOT triggered (used when importing from server).
 */
export function AddHistory(word: string, result: string): $CancellablePromise<void> {
    return $Call.ByID(3292216004, word, result);
}

/**
 * AddHistoryFromSync adds/updates an entry from a server pull, without triggering
 * the sync callback (to avoid pushing it right back to the server).
 */
export function AddHistoryFromSync(word: string, result: string): $CancellablePromise<void> {
    return $Call.ByID(3813569295, word, result);
}

/**
 * ClearHistory removes all entries
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(671203826);
}

/**
 * DeleteHistory removes an entry by ID
 */
export function DeleteHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(746899210, id);
}

/**
 * GetAllEntriesForSync returns all entries formatted for sync push
 */
export function GetAllEntriesForSync(): $CancellablePromise<$models.HistoryEntry[] | null> {
    return $Call.ByID(4192341606);
}

/**
 * GetDB returns the underlying database connection (for sync service use)
 */
export function GetDB(): $CancellablePromise<sql$0.DB | null> {
    return $Call.ByID(1288756641);
}

/**
 * GetHistory returns all entries (newest first)
 */
export function GetHistory(): $CancellablePromise<$models.HistoryEntry[] | null> {
    return $Call.ByID(3254780633);
}

/**
 * GetHistoryByWord returns a single entry by word (case-insensitive).
 * Used for cache lookup to avoid redundant LLM calls.
 */
export function GetHistoryByWord(word: string): $CancellablePromise<$models.HistoryEntry | null> {
    return $Call.ByID(3200924104, word);
}

/**
 * GetHistoryEntry returns a single entry by ID
 */
export function GetHistoryEntry(id: string): $CancellablePromise<$models.HistoryEntry | null> {
    return $Call.ByID(193250743, id);
}
