systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7993
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7993
systemProp.http.nonProxyHosts=localhost|127.0.0.1
org.gradle.jvmargs=-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7993 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7993 -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djavax.net.ssl.trustStoreType=Windows-ROOT
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

org.gradle.network.stack=JAVA
