// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetConfig returns current configuration
 */
export function GetConfig(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(722970649);
}

/**
 * GetPromptConfig returns the current prompt configuration as a JSON string.
 */
export function GetPromptConfig(): $CancellablePromise<string> {
    return $Call.ByID(3674654971);
}

/**
 * IsEnglishText checks if text is English word/phrase
 */
export function IsEnglishText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(1586785840, text);
}

/**
 * LookupWord is the legacy combined method (kept for backward compat).
 * It first tries ECDICT, then LLM, returning the merged result.
 */
export function LookupWord(word: string): $CancellablePromise<string> {
    return $Call.ByID(688235267, word);
}

/**
 * LookupWordFast returns ECDICT result immediately (offline, ~10ms).
 * Returns JSON string of the ECDICT entry, or empty string if not found.
 */
export function LookupWordFast(word: string): $CancellablePromise<string> {
    return $Call.ByID(1099801581, word);
}

/**
 * LookupWordLLM calls LLM to get enriched word definition.
 * This is the slow path (~2-10s), called after ECDICT fast result is shown.
 */
export function LookupWordLLM(word: string): $CancellablePromise<string> {
    return $Call.ByID(1393846922, word);
}

/**
 * ReadClipboard reads text from system clipboard
 */
export function ReadClipboard(): $CancellablePromise<string> {
    return $Call.ByID(164120933);
}

/**
 * SaveConfig saves API configuration
 */
export function SaveConfig(apiKey: string, apiURL: string, modelName: string, shortcutKey: string): $CancellablePromise<void> {
    return $Call.ByID(404939594, apiKey, apiURL, modelName, shortcutKey);
}

/**
 * SavePromptConfig saves the prompt configuration (provided as a JSON string).
 */
export function SavePromptConfig(configJSON: string): $CancellablePromise<void> {
    return $Call.ByID(2832855076, configJSON);
}

/**
 * TestPrompt builds a prompt from the given config JSON and calls the LLM for a test word.
 * Returns the raw LLM JSON response (same cleaning as LookupWordLLM).
 */
export function TestPrompt(word: string, configJSON: string): $CancellablePromise<string> {
    return $Call.ByID(972792879, word, configJSON);
}
