// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CacheResult stores a merged lookup result in the in-memory cache.
 * Call this after a successful full lookup so subsequent lookups of the same
 * word are served from cache instantly.
 * @param {string} word
 * @param {string} result
 * @returns {$CancellablePromise<void>}
 */
export function CacheResult(word, result) {
    return $Call.ByID(4117976504, word, result);
}

/**
 * GetAutoStart returns whether auto-start is currently enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoStart() {
    return $Call.ByID(1447106028);
}

/**
 * GetCacheStats returns cache statistics for debugging.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetCacheStats() {
    return $Call.ByID(3663779730).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetConfig returns current configuration
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetConfig() {
    return $Call.ByID(722970649).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetPromptConfig returns the current prompt configuration as a JSON string.
 * @returns {$CancellablePromise<string>}
 */
export function GetPromptConfig() {
    return $Call.ByID(3674654971);
}

/**
 * GetPromptDebugInfo returns the exact system and user prompts that would be sent
 * for a given word, without actually calling the LLM. Useful for debugging
 * prompt cache behavior and prompt structure.
 * @param {string} word
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetPromptDebugInfo(word) {
    return $Call.ByID(937010968, word).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * IsEnglishText checks if text is English word/phrase
 * @param {string} text
 * @returns {$CancellablePromise<boolean>}
 */
export function IsEnglishText(text) {
    return $Call.ByID(1586785840, text);
}

/**
 * LookupWord is the legacy combined method (kept for backward compat).
 * It first tries ECDICT, then LLM, returning the merged result.
 * @param {string} word
 * @returns {$CancellablePromise<string>}
 */
export function LookupWord(word) {
    return $Call.ByID(688235267, word);
}

/**
 * LookupWordCached checks the in-memory cache and history DB for a previously
 * looked-up word. Returns the full merged JSON result (ECDICT+LLM) if found,
 * or empty string if not cached. This avoids redundant LLM calls for words
 * the user has already looked up.
 * @param {string} word
 * @returns {$CancellablePromise<string>}
 */
export function LookupWordCached(word) {
    return $Call.ByID(719803657, word);
}

/**
 * LookupWordFast returns ECDICT result immediately (offline, ~10ms).
 * Returns JSON string of the ECDICT entry, or empty string if not found.
 * @param {string} word
 * @returns {$CancellablePromise<string>}
 */
export function LookupWordFast(word) {
    return $Call.ByID(1099801581, word);
}

/**
 * LookupWordLLM calls LLM to get enriched word definition.
 * This is the slow path (~2-10s), called after ECDICT fast result is shown.
 * @param {string} word
 * @returns {$CancellablePromise<string>}
 */
export function LookupWordLLM(word) {
    return $Call.ByID(1393846922, word);
}

/**
 * LookupWordLLMFast calls LLM without re-querying ECDICT for the prompt context.
 * Use this when the frontend already has the ECDICT data from LookupWordFast.
 * @param {string} word
 * @returns {$CancellablePromise<string>}
 */
export function LookupWordLLMFast(word) {
    return $Call.ByID(2620384208, word);
}

/**
 * ReadClipboard reads text from system clipboard
 * @returns {$CancellablePromise<string>}
 */
export function ReadClipboard() {
    return $Call.ByID(164120933);
}

/**
 * SaveConfig saves API configuration
 * @param {string} apiKey
 * @param {string} apiURL
 * @param {string} modelName
 * @param {string} shortcutKey
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(apiKey, apiURL, modelName, shortcutKey) {
    return $Call.ByID(404939594, apiKey, apiURL, modelName, shortcutKey);
}

/**
 * SavePromptConfig saves the prompt configuration (provided as a JSON string).
 * @param {string} configJSON
 * @returns {$CancellablePromise<void>}
 */
export function SavePromptConfig(configJSON) {
    return $Call.ByID(2832855076, configJSON);
}

/**
 * SetAutoStart enables or disables auto-start on system boot.
 * On Windows it writes/removes a Run registry key under HKCU.
 * @param {boolean} enable
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoStart(enable) {
    return $Call.ByID(2918338240, enable);
}

/**
 * TestPrompt builds a prompt from the given config JSON and calls the LLM for a test word.
 * Returns the raw LLM JSON response (same cleaning as LookupWordLLM).
 * @param {string} word
 * @param {string} configJSON
 * @returns {$CancellablePromise<string>}
 */
export function TestPrompt(word, configJSON) {
    return $Call.ByID(972792879, word, configJSON);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
