// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetConfig returns current configuration
 */
export function GetConfig(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(722970649);
}

/**
 * IsEnglishText checks if text is English word/phrase
 */
export function IsEnglishText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(1586785840, text);
}

/**
 * LookupWord calls LLM to get word definition
 */
export function LookupWord(word: string): $CancellablePromise<string> {
    return $Call.ByID(688235267, word);
}

/**
 * ReadClipboard reads text from system clipboard
 */
export function ReadClipboard(): $CancellablePromise<string> {
    return $Call.ByID(164120933);
}

/**
 * SaveConfig saves API configuration
 */
export function SaveConfig(apiKey: string, apiURL: string, modelName: string, shortcutKey: string): $CancellablePromise<void> {
    return $Call.ByID(404939594, apiKey, apiURL, modelName, shortcutKey);
}
