// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CacheResult stores a merged lookup result in the in-memory cache.
 * Call this after a successful full lookup so subsequent lookups of the same
 * word are served from cache instantly.
 */
export function CacheResult(word: string, result: string): $CancellablePromise<void> {
    return $Call.ByID(4117976504, word, result);
}

/**
 * GetAutoStart returns whether auto-start is currently enabled.
 */
export function GetAutoStart(): $CancellablePromise<boolean> {
    return $Call.ByID(1447106028);
}

/**
 * GetCacheStats returns cache statistics for debugging.
 */
export function GetCacheStats(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3663779730);
}

/**
 * GetConfig returns current configuration
 */
export function GetConfig(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(722970649);
}

/**
 * GetPromptConfig returns the current prompt configuration as a JSON string.
 */
export function GetPromptConfig(): $CancellablePromise<string> {
    return $Call.ByID(3674654971);
}

/**
 * GetPromptDebugInfo returns the exact system and user prompts that would be sent
 * for a given word, without actually calling the LLM. Useful for debugging
 * prompt cache behavior and prompt structure.
 */
export function GetPromptDebugInfo(word: string): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(937010968, word);
}

/**
 * IsEnglishText checks if text is English word/phrase
 */
export function IsEnglishText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(1586785840, text);
}

/**
 * LookupWord is the legacy combined method (kept for backward compat).
 * It first tries ECDICT, then LLM, returning the merged result.
 */
export function LookupWord(word: string): $CancellablePromise<string> {
    return $Call.ByID(688235267, word);
}

/**
 * LookupWordCached checks the in-memory cache and history DB for a previously
 * looked-up word. Returns the full merged JSON result (ECDICT+LLM) if found,
 * or empty string if not cached. This avoids redundant LLM calls for words
 * the user has already looked up.
 */
export function LookupWordCached(word: string): $CancellablePromise<string> {
    return $Call.ByID(719803657, word);
}

/**
 * LookupWordFast returns ECDICT result immediately (offline, ~10ms).
 * Returns JSON string of the ECDICT entry, or empty string if not found.
 */
export function LookupWordFast(word: string): $CancellablePromise<string> {
    return $Call.ByID(1099801581, word);
}

/**
 * LookupWordLLM calls LLM to get enriched word definition.
 * This is the slow path (~2-10s), called after ECDICT fast result is shown.
 */
export function LookupWordLLM(word: string): $CancellablePromise<string> {
    return $Call.ByID(1393846922, word);
}

/**
 * LookupWordLLMFast calls LLM without re-querying ECDICT for the prompt context.
 * Use this when the frontend already has the ECDICT data from LookupWordFast.
 */
export function LookupWordLLMFast(word: string): $CancellablePromise<string> {
    return $Call.ByID(2620384208, word);
}

/**
 * ReadClipboard reads text from system clipboard
 */
export function ReadClipboard(): $CancellablePromise<string> {
    return $Call.ByID(164120933);
}

/**
 * SaveConfig saves API configuration
 */
export function SaveConfig(apiKey: string, apiURL: string, modelName: string, shortcutKey: string): $CancellablePromise<void> {
    return $Call.ByID(404939594, apiKey, apiURL, modelName, shortcutKey);
}

/**
 * SavePromptConfig saves the prompt configuration (provided as a JSON string).
 */
export function SavePromptConfig(configJSON: string): $CancellablePromise<void> {
    return $Call.ByID(2832855076, configJSON);
}

/**
 * SetAutoStart enables or disables auto-start on system boot.
 * On Windows it writes/removes a Run registry key under HKCU.
 */
export function SetAutoStart(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(2918338240, enable);
}

/**
 * TestPrompt builds a prompt from the given config JSON and calls the LLM for a test word.
 * Returns the raw LLM JSON response (same cleaning as LookupWordLLM).
 */
export function TestPrompt(word: string, configJSON: string): $CancellablePromise<string> {
    return $Call.ByID(972792879, word, configJSON);
}
