// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService manages the local word book using SQLite.
 * It replaces the old JSON-file-based history with proper database storage,
 * enabling reliable persistence and sync support.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../database/sql/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddHistory adds a new entry or updates an existing one (same word).
 * If skipSync is true, the sync callback is NOT triggered (used when importing from server).
 * @param {string} word
 * @param {string} result
 * @returns {$CancellablePromise<void>}
 */
export function AddHistory(word, result) {
    return $Call.ByID(3292216004, word, result);
}

/**
 * AddHistoryFromSync adds/updates an entry from a server pull, without triggering
 * the sync callback (to avoid pushing it right back to the server).
 * @param {string} word
 * @param {string} result
 * @returns {$CancellablePromise<void>}
 */
export function AddHistoryFromSync(word, result) {
    return $Call.ByID(3813569295, word, result);
}

/**
 * ClearHistory removes all entries
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory() {
    return $Call.ByID(671203826);
}

/**
 * DeleteHistory removes an entry by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteHistory(id) {
    return $Call.ByID(746899210, id);
}

/**
 * GetAllEntriesForSync returns all entries formatted for sync push
 * @returns {$CancellablePromise<$models.HistoryEntry[]>}
 */
export function GetAllEntriesForSync() {
    return $Call.ByID(4192341606).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetDB returns the underlying database connection (for sync service use)
 * @returns {$CancellablePromise<sql$0.DB | null>}
 */
export function GetDB() {
    return $Call.ByID(1288756641).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetHistory returns all entries (newest first)
 * @returns {$CancellablePromise<$models.HistoryEntry[]>}
 */
export function GetHistory() {
    return $Call.ByID(3254780633).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetHistoryByWord returns a single entry by word (case-insensitive).
 * Used for cache lookup to avoid redundant LLM calls.
 * @param {string} word
 * @returns {$CancellablePromise<$models.HistoryEntry | null>}
 */
export function GetHistoryByWord(word) {
    return $Call.ByID(3200924104, word).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetHistoryEntry returns a single entry by ID
 * @param {string} id
 * @returns {$CancellablePromise<$models.HistoryEntry | null>}
 */
export function GetHistoryEntry(id) {
    return $Call.ByID(193250743, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.HistoryEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = sql$0.DB.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Nullable($$createType0);
