// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddHistory adds a new entry
 */
export function AddHistory(word: string, result: string): $CancellablePromise<void> {
    return $Call.ByID(3292216004, word, result);
}

/**
 * ClearHistory removes all entries
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(671203826);
}

/**
 * DeleteHistory removes an entry by ID
 */
export function DeleteHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(746899210, id);
}

/**
 * GetHistory returns all entries (newest first)
 */
export function GetHistory(): $CancellablePromise<$models.HistoryEntry[] | null> {
    return $Call.ByID(3254780633);
}

/**
 * GetHistoryEntry returns a single entry by ID
 */
export function GetHistoryEntry(id: string): $CancellablePromise<$models.HistoryEntry | null> {
    return $Call.ByID(193250743, id);
}
