// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DictService from "./dictservice.js";
import * as HistoryService from "./historyservice.js";
export {
    DictService,
    HistoryService
};

export type {
    HistoryEntry
} from "./models.js";
