// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DictService from "./dictservice.js";
import * as EcdictService from "./ecdictservice.js";
import * as HistoryService from "./historyservice.js";
import * as SyncService from "./syncservice.js";
export {
    DictService,
    EcdictService,
    HistoryService,
    SyncService
};

export type {
    EcdictEntry,
    HistoryEntry
} from "./models.js";
