// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface HistoryEntry {
    "id": string;
    "word": string;
    "result": string;
    "createdAt": string;
}
