// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EcdictEntry represents a row from the ECDICT database
 */
export interface EcdictEntry {
    "word": string;
    "phonetic": string;

    /**
     * English definitions (newline-separated)
     */
    "definition": string;

    /**
     * Chinese definitions (newline-separated)
     */
    "translation": string;

    /**
     * Part of speech
     */
    "pos": string;

    /**
     * Collins star rating 1-5
     */
    "collins": number | null;

    /**
     * Oxford 3000 flag
     */
    "oxford": number | null;

    /**
     * Exam tags: "cet4 cet6 gre toefl"
     */
    "tag": string;

    /**
     * BNC frequency rank
     */
    "bnc": number | null;

    /**
     * Contemporary corpus frequency rank
     */
    "frq": number | null;

    /**
     * Inflected forms: "d:abandoned/p:abandoned/i:abandoning/3:abandons"
     */
    "exchange": string;
}

/**
 * ============================================================
 * HistoryEntry represents a saved word with its full lookup result.
 * This is the core data model for the local word book and sync.
 */
export interface HistoryEntry {
    /**
     * Unique ID (nanosecond timestamp)
     */
    "id": string;

    /**
     * The looked-up word
     */
    "word": string;

    /**
     * JSON string of merged ECDICT+LLM result
     */
    "result": string;

    /**
     * Unix timestamp (seconds)
     */
    "createdAt": number;

    /**
     * Unix timestamp (seconds)
     */
    "updatedAt": number;
}
