// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EcdictEntry represents a row from the ECDICT database
 */
export class EcdictEntry {
    /**
     * Creates a new EcdictEntry instance.
     * @param {Partial<EcdictEntry>} [$$source = {}] - The source object to create the EcdictEntry.
     */
    constructor($$source = {}) {
        if (!("word" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["word"] = "";
        }
        if (!("phonetic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phonetic"] = "";
        }
        if (!("definition" in $$source)) {
            /**
             * English definitions (newline-separated)
             * @member
             * @type {string}
             */
            this["definition"] = "";
        }
        if (!("translation" in $$source)) {
            /**
             * Chinese definitions (newline-separated)
             * @member
             * @type {string}
             */
            this["translation"] = "";
        }
        if (!("pos" in $$source)) {
            /**
             * Part of speech
             * @member
             * @type {string}
             */
            this["pos"] = "";
        }
        if (!("collins" in $$source)) {
            /**
             * Collins star rating 1-5
             * @member
             * @type {number | null}
             */
            this["collins"] = null;
        }
        if (!("oxford" in $$source)) {
            /**
             * Oxford 3000 flag
             * @member
             * @type {number | null}
             */
            this["oxford"] = null;
        }
        if (!("tag" in $$source)) {
            /**
             * Exam tags: "cet4 cet6 gre toefl"
             * @member
             * @type {string}
             */
            this["tag"] = "";
        }
        if (!("bnc" in $$source)) {
            /**
             * BNC frequency rank
             * @member
             * @type {number | null}
             */
            this["bnc"] = null;
        }
        if (!("frq" in $$source)) {
            /**
             * Contemporary corpus frequency rank
             * @member
             * @type {number | null}
             */
            this["frq"] = null;
        }
        if (!("exchange" in $$source)) {
            /**
             * Inflected forms: "d:abandoned/p:abandoned/i:abandoning/3:abandons"
             * @member
             * @type {string}
             */
            this["exchange"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EcdictEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EcdictEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EcdictEntry(/** @type {Partial<EcdictEntry>} */($$parsedSource));
    }
}

/**
 * ============================================================
 * HistoryEntry represents a saved word with its full lookup result.
 * This is the core data model for the local word book and sync.
 */
export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * Unique ID (nanosecond timestamp)
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("word" in $$source)) {
            /**
             * The looked-up word
             * @member
             * @type {string}
             */
            this["word"] = "";
        }
        if (!("result" in $$source)) {
            /**
             * JSON string of merged ECDICT+LLM result
             * @member
             * @type {string}
             */
            this["result"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * Unix timestamp (seconds)
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * Unix timestamp (seconds)
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}
