// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateUser creates a new user on the remote server and returns the token (legacy).
 */
export function CreateUser(): $CancellablePromise<string> {
    return $Call.ByID(3310874217);
}

/**
 * GetSyncConfig returns current sync configuration
 */
export function GetSyncConfig(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2385525567);
}

/**
 * OnEntryAdded is called by HistoryService when a new entry is saved.
 * If auto-sync is enabled, it pushes the entry to the server in the background.
 */
export function OnEntryAdded(entry: $models.HistoryEntry): $CancellablePromise<void> {
    return $Call.ByID(1359595909, entry);
}

/**
 * PollQrCodeStatus polls the sync server for QR code login status.
 * Returns a map with "status" ("pending" | "scanned" | "expired") and
 * optionally "token" (when status is "scanned").
 * If the user has scanned the QR code, this method auto-saves the token.
 */
export function PollQrCodeStatus(scene: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2851263155, scene);
}

/**
 * PullFromServer pulls entries from the remote sync server and merges into local history.
 * Uses incremental sync: only pulls entries updated since the last successful sync.
 * Falls back to full pull if never synced before.
 */
export function PullFromServer(): $CancellablePromise<string> {
    return $Call.ByID(1176688374);
}

/**
 * PushToServer pushes all local history entries to the remote sync server.
 */
export function PushToServer(): $CancellablePromise<string> {
    return $Call.ByID(2584984300);
}

/**
 * RequestQrCode requests a QR code login session from the sync server.
 * Returns a map with "scene", "expiresIn", and optionally "qrcode" (base64 PNG data URL).
 * The desktop app should display the QR code image (or the scene string as fallback)
 * and then poll with PollQrCodeStatus until the user scans it.
 */
export function RequestQrCode(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3435864157);
}

/**
 * SaveSyncConfig saves sync configuration
 */
export function SaveSyncConfig(syncAddr: string, syncToken: string, autoSync: boolean): $CancellablePromise<void> {
    return $Call.ByID(882092646, syncAddr, syncToken, autoSync);
}

/**
 * TestConnection tests the connection to the sync server.
 * Returns a human-readable status message.
 */
export function TestConnection(): $CancellablePromise<string> {
    return $Call.ByID(776402662);
}
