// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateUser creates a new user on the remote server and returns the token.
 */
export function CreateUser(): $CancellablePromise<string> {
    return $Call.ByID(3310874217);
}

/**
 * GetSyncConfig returns current sync configuration
 */
export function GetSyncConfig(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2385525567);
}

/**
 * OnEntryAdded is called by HistoryService when a new entry is saved.
 * If auto-sync is enabled, it pushes the entry to the server in the background.
 */
export function OnEntryAdded(entry: $models.HistoryEntry): $CancellablePromise<void> {
    return $Call.ByID(1359595909, entry);
}

/**
 * PullFromServer pulls entries from the remote sync server and merges into local history.
 */
export function PullFromServer(): $CancellablePromise<string> {
    return $Call.ByID(1176688374);
}

/**
 * PushToServer pushes all local history entries to the remote sync server.
 */
export function PushToServer(): $CancellablePromise<string> {
    return $Call.ByID(2584984300);
}

/**
 * SaveSyncConfig saves sync configuration
 */
export function SaveSyncConfig(syncAddr: string, syncToken: string, autoSync: boolean): $CancellablePromise<void> {
    return $Call.ByID(882092646, syncAddr, syncToken, autoSync);
}

/**
 * TestConnection tests the connection to the sync server.
 * Returns a human-readable status message.
 */
export function TestConnection(): $CancellablePromise<string> {
    return $Call.ByID(776402662);
}
