// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateUser creates a new user on the remote server and returns the token.
 * @returns {$CancellablePromise<string>}
 */
export function CreateUser() {
    return $Call.ByID(3310874217);
}

/**
 * GetSyncConfig returns current sync configuration
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetSyncConfig() {
    return $Call.ByID(2385525567).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OnEntryAdded is called by HistoryService when a new entry is saved.
 * If auto-sync is enabled, it pushes the entry to the server in the background.
 * @param {$models.HistoryEntry} entry
 * @returns {$CancellablePromise<void>}
 */
export function OnEntryAdded(entry) {
    return $Call.ByID(1359595909, entry);
}

/**
 * PullFromServer pulls entries from the remote sync server and merges into local history.
 * Uses incremental sync: only pulls entries updated since the last successful sync.
 * Falls back to full pull if never synced before.
 * @returns {$CancellablePromise<string>}
 */
export function PullFromServer() {
    return $Call.ByID(1176688374);
}

/**
 * PushToServer pushes all local history entries to the remote sync server.
 * @returns {$CancellablePromise<string>}
 */
export function PushToServer() {
    return $Call.ByID(2584984300);
}

/**
 * SaveSyncConfig saves sync configuration
 * @param {string} syncAddr
 * @param {string} syncToken
 * @param {boolean} autoSync
 * @returns {$CancellablePromise<void>}
 */
export function SaveSyncConfig(syncAddr, syncToken, autoSync) {
    return $Call.ByID(882092646, syncAddr, syncToken, autoSync);
}

/**
 * TestConnection tests the connection to the sync server.
 * Returns a human-readable status message.
 * @returns {$CancellablePromise<string>}
 */
export function TestConnection() {
    return $Call.ByID(776402662);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
