const config = require('./utils/config')
const sync = require('./utils/sync')
const store = require('./utils/store')
const fsrsEngine = require('./utils/fsrs-engine')

App({
  globalData: {
    serverAddr: '',
    token: '',
    serverNow: 0,
    syncPromise: null,  // ongoing sync promise, pages can await it
    pendingScene: null   // scene from QR code launch, consumed by index page
  },

  onLaunch(options) {
    const cfg = config.load()
    this.globalData.serverAddr = cfg.serverAddr
    this.globalData.token = cfg.token

    // Handle scene parameter from QR code scan
    // When user scans the WeChat QR code generated by the desktop app,
    // the mini program opens with the scene value in options.scene
    if (options && options.scene) {
      // Decode the scene value (WeChat may URL-encode it)
      let scene = options.scene
      try {
        scene = decodeURIComponent(scene)
      } catch (e) {
        // use as-is if decode fails
      }
      console.log('App: received scene from QR code:', scene)
      this.globalData.pendingScene = scene
    }

    // Start auto sync (pages can await globalData.syncPromise)
    this.globalData.syncPromise = this.autoSync()

    // If server is configured and there are due cards, go straight to review
    if (cfg.serverAddr && cfg.token) {
      const words = store.getWords()
      const reviews = store.getReviews()
      const dueCount = fsrsEngine.getQueueCounts(words, reviews).total
      if (dueCount > 0) {
        wx.redirectTo({ url: '/pages/review/review' })
      }
    }
  },

  setConfig(serverAddr, token) {
    this.globalData.serverAddr = serverAddr
    this.globalData.token = token
    config.save(serverAddr, token)
  },

  // Perform WeChat login: call wx.login() then send code+scene to server
  // Returns the token on success, throws on failure
  async doWeChatLogin(scene) {
    const { serverAddr } = this.globalData
    if (!serverAddr) {
      throw new Error('Server address not configured')
    }

    // Step 1: Get temporary login code from WeChat
    const loginRes = await new Promise((resolve, reject) => {
      wx.login({
        success: resolve,
        fail: reject
      })
    })

    if (!loginRes.code) {
      throw new Error('wx.login failed: no code returned')
    }

    // Step 2: Send code + scene to our sync server
    const result = await sync.wechatLogin(serverAddr, loginRes.code, scene)

    if (result.token) {
      // Save the token
      this.setConfig(serverAddr, result.token)
      return result.token
    }

    throw new Error(result.message || 'Login failed: no token returned')
  },

  // Auto sync on launch: full pull if never synced, delta otherwise
  async autoSync() {
    const { serverAddr, token } = this.globalData
    if (!serverAddr || !token) return null

    const since = store.getLastSync()
    try {
      const res = await sync.pull(serverAddr, token, since || 0)
      const r = store.mergePulled(res.entries || [], res.serverNow)
      if (r.changed > 0) {
        console.log('Auto sync: ' + r.changed + ' entries updated')
      }
      return { changed: r.changed, total: r.total, serverNow: res.serverNow }
    } catch (e) {
      // Best-effort, silent failure
      return null
    }
  }
})
